export const FUNCTION_PRESETS = [
  { name: "Double cliff", value: "1 / ((x * x + 1)) + 1 / ((y * y + 1))" },
  { name: "Sinusoidal wave", value: "Math.sin(x * 2) * Math.cos(y * 2)" },
  { name: "Radial wave", value: "Math.sin(Math.sqrt(x * x + y * y) * 5)" },
  { name: "Cross waves", value: "Math.sin(x) + Math.sin(y)" },
  { name: "Square radial wave", value: "Math.sin(x * x - y * y)" },
  {
    name: "Spiral explosion",
    value: "Math.sin(10 * Math.atan2(y, x)) * Math.exp(-x * x - y * y)",
  },
  { name: "Grid peaks", value: "Math.sin(10 * x) * Math.sin(10 * y)" },
  { name: "Fractal mountains", value: "Math.sin(x*y) * Math.cos(x + y)" },
  { name: "Polar vortex", value: "Math.atan2(y, x) * Math.sqrt(x*x + y*y)" },
  {
    name: "Jagged ridges",
    value: "Math.abs(Math.sin(3 * x) + Math.sin(3 * y))",
  },
  { name: "Diagonal valleys", value: "Math.cos(x + y)" },
  { name: "Sinusoidal pit", value: "-Math.abs(Math.sin(x) * Math.cos(y))" },
  { name: "Interference field", value: "Math.sin(x * y) * Math.sin(y)" },
  {
    name: "Square wave",
    value: "Math.sign(Math.sin(x)) + Math.sign(Math.cos(y))",
  },
  { name: "Inverted cone", value: "-Math.sqrt(x*x + y*y)" },
  {
    name: "Crossed spiral",
    value:
      "Math.sin(2 * Math.atan2(y, x)) + Math.cos(3 * Math.sqrt(x*x + y*y))",
  },
  {
    name: "Wavy spiral",
    value: "Math.sin(4 * Math.atan2(y, x)) * Math.sqrt(x*x + y*y)",
  },
  {
    name: "Logarithmic spiral",
    value: "Math.sin(Math.atan2(y, x) + 4 * Math.log(1 + x*x + y*y))",
  },
  {
    name: "Spiral staircase",
    value: "Math.floor(5 * Math.atan2(y, x)) + Math.sqrt(x*x + y*y)",
  },
  {
    name: "Spiral staircase",
    value: "Math.floor(5 * Math.atan2(y, x)) + Math.sqrt(x*x + y*y)",
  },
  { name: "Radial grid", value: "Math.cos(Math.sqrt(Math.abs(x * y)))" },
  {
    name: "Disturbed vortex",
    value: "Math.atan2(y, x) + Math.sin(3 * Math.sqrt(x*x + y*y))",
  },
  {
    name: "Distorted dynamic",
    value: "(x * Math.sin(y) + y * Math.cos(x)) / 2",
  },
  {
    name: "Vibrant flower",
    value: "3*Math.exp(-Math.abs(x*y)) * Math.sin(4*x) * Math.cos(4*y)",
  },
  { name: "Cubic field", value: "Math.pow(Math.sin(x*x + y*y), 3)" },
  {
    name: "Diagonal stripes",
    value: "Math.abs(Math.sin(x * y)) * Math.sign(x - y)",
  },
  {
    name: "Interfering lenses",
    value: "Math.sin(10 * (x*x - y*y)) / (10 + x*x + y*y)",
  },
  {
    name: "Cut wave",
    value: "Math.sign(x*y) * Math.sin(Math.sqrt(Math.abs(x - y)))",
  },
  { name: "Circular torsion", value: "Math.atan2(Math.sin(y), Math.cos(x))" },
  {
    name: "Radial wake",
    value: "Math.sin(Math.sqrt(x*x + y*y)) * Math.cos(Math.atan2(y, x))",
  },
  {
    name: "Soft cymatics",
    value:
      "Math.exp(-Math.pow(x*x + y*y, 0.3)) * Math.sin(6 * Math.sqrt(x*x + y*y))",
  },
  {
    name: "Fractal vortex",
    value: "(Math.atan2(x, y) * Math.sin(x*x + y*y)) / 2",
  },
  { name: "Nested pattern", value: "Math.sin(x + y + Math.sin(x*y))" },
  {
    name: "Yin-yang wave",
    value: "Math.sin(x) * Math.sin(y) + Math.cos(x + y)",
  },
  {
    name: "Wavy balance",
    value: "Math.sin(Math.atan2(y, x) + Math.sqrt(x*x + y*y))",
  },
  {
    name: "Inverted symmetry",
    value: "Math.sin(x*x - y*y) * Math.cos(2 * x * y)",
  },
  {
    name: "Celtic interlace",
    value: "Math.sin(Math.atan2(y, x) * 3) * Math.cos(Math.sqrt(x*x + y*y))",
  },
  { name: "Disturbed vortex", value: "Math.atan2(y, x) + Math.sin(x*x + y*y)" },
  {
    name: "Woven spiral",
    value: "Math.sin(5 * Math.atan2(y, x)) * Math.sin(2 * Math.sqrt(x*x +y*y))",
  },
];

export const PARAMETRIC_PRESETS = [
  {
    name: "Torus",
    x: "(2 + Math.cos(v)) * Math.cos(u)",
    y: "(2 + Math.cos(v)) * Math.sin(u)",
    z: "Math.sin(v)",
    uMin: 0,
    uMax: 6.28,
    vMin: 0,
    vMax: 6.28,
  },
  {
    name: "Mobius Strip",
    x: "(1 + 0.5 * Math.cos(v)) * Math.cos(u)",
    y: "(1 + 0.5 * Math.cos(v)) * Math.sin(u)",
    z: "0.5 * Math.sin(v)",
    uMin: 0,
    uMax: 6.28,
    vMin: -3.14,
    vMax: 3.14,
  },

  {
    name: "Hyperbolic Paraboloid",
    x: "u",
    y: "v",
    z: "u * u - v * v",
    uMin: -2,
    uMax: 2,
    vMin: -2,
    vMax: 2,
  },
  {
    name: "Helicoid",
    x: "u * Math.cos(v)",
    y: "u * Math.sin(v)",
    z: "v",
    uMin: -2,
    uMax: 2,
    vMin: -3.14,
    vMax: 3.14,
  },
  {
    name: "Twisted Band",
    x: "(1 + 0.3 * Math.cos(v)) * Math.cos(u)",
    y: "(1 + 0.3 * Math.cos(v)) * Math.sin(u)",
    z: "0.3 * Math.sin(v)",
    uMin: 0,
    uMax: 6.28,
    vMin: 0,
    vMax: 12.56,
  },
  {
    name: "Ripple Disk",
    x: "u * Math.cos(v)",
    y: "u * Math.sin(v)",
    z: "0.2 * Math.sin(10 * u)",
    uMin: 0,
    uMax: 2,
    vMin: 0,
    vMax: 6.28,
  },
  {
    name: "Trefoil Knot Surface",
    x: "(2 + Math.cos(3 * v)) * Math.cos(2 * u)",
    y: "(2 + Math.cos(3 * v)) * Math.sin(2 * u)",
    z: "Math.sin(3 * v)",
    uMin: 0,
    uMax: 6.28,
    vMin: 0,
    vMax: 6.28,
  },
  {
    name: "Catenoid",
    x: "Math.cosh(u) * Math.cos(v)",
    y: "Math.cosh(u) * Math.sin(v)",
    z: "u",
    uMin: -1.5,
    uMax: 1.5,
    vMin: 0,
    vMax: 6.28,
  },
  {
    name: "Trumpet Flare",
    x: "u * Math.cos(v)",
    y: "u * Math.sin(v)",
    z: "Math.log(1 + u * u)",
    uMin: 0.1,
    uMax: 2,
    vMin: 0,
    vMax: 6.28,
  },
  {
    name: "Flower Disk",
    x: "u * Math.cos(v) * (1 + 0.3 * Math.cos(6 * v))",
    y: "u * Math.sin(v) * (1 + 0.3 * Math.cos(6 * v))",
    z: "0.2 * Math.sin(6 * v)",
    uMin: 0,
    uMax: 1.5,
    vMin: 0,
    vMax: 6.28,
  },
  {
    name: "Enneper Surface",
    x: "u - (u ** 3) / 3 + u * v * v",
    y: "v - (v ** 3) / 3 + v * u * u",
    z: "u * u - v * v",
    uMin: -1.5,
    uMax: 1.5,
    vMin: -1.5,
    vMax: 1.5,
  },
  {
    name: "Curtain Waves",
    x: "u",
    y: "Math.sin(3 * u + v)",
    z: "v",
    uMin: -3,
    uMax: 3,
    vMin: -2,
    vMax: 2,
  },
];
